open-webrtc-toolkit/owt-server

- scripts/installCommonDeps.sh
- source/agent/conference/package.json
- source/management_api/package.json
- source/portal/package.json
> Fix node deps issues

- scripts/installCommonDeps.sh
- scripts/installDeps.sh
- source/agent/audio/audioMixer/AcmmOutput.cpp
- source/core/owt_base/VideoFramePacketizer.cpp
- third_party/mediasdk/samples/sample_common/src/vaapi_allocator.cpp
1. remove vainfo install script
2. fix ubuntu 18.04 build warning
> Code cleanup

- source/agent/analytics/dist.json
- source/agent/analytics/index.js
- source/agent/workingNode.js
Align analytics agent's arguments with other agents
> Align analytics agent's arguments with other agents

- source/core/owt_base/AVStreamOut.cpp
- source/core/owt_base/AVStreamOut.h
1. Set valid AVPacket duration
2. Optimize video key frame request interval
> Fix dash output issue

- scripts/installUbuntuDeps.sh
- source/common/cipher.js
1. Remove deprecated warning when using cipher
2. Remove unused libssl-dev in installUbuntuDeps.sh
> Update to the latest recommanded crypto use

- doc/servermd/Server.md
Change description of SVT-HEVC encoder
> Change description of SVT-HEVC encoder

- doc/doxygen_cfrc.conf
- doc/doxygen_cp.conf
- doc/doxygen_rest.conf
- doc/servermd/RESTAPI.md
- doc/servermd/Server.md
> doc change

- doc/servermd/RESTAPI.md
- doc/servermd/Server.md
> Unify some formats in doc

- source/data_access/model/roomModel.js
Fix SIP portal issue when create room
> Fix SIP portal issue when create room

- scripts/installCommonDeps.sh
- scripts/installDeps.sh
- scripts/installDepsUnattended.sh
> Add incremental and only target option in dependency install scripts

- source/agent/webrtc/wrtcConnection.js
- source/core/owt_base/VideoFramePacketizer.cpp
- source/core/owt_base/VideoFramePacketizer.h
Adjust timestamp in packetizer for stream substitution
> Adjust timestamp in packetizer for stream substitution

- source/agent/webrtc/wrtcConnection.js
Disable transport-cc for subscribe connections
> Disable transport-cc for subscribe connections

- scripts/installCommonDeps.sh
- scripts/pack.js
- source/agent/addons/internalIO/binding.gyp
- source/agent/sip/sipIn/binding.sip.gyp
- source/agent/sip/sipIn/sip_gateway/sipua/Makefile
Move some third_party dependencies to build dir
> Move some third_party dependencies to build dir

- source/data_access/interface/roomInterface.js
Fix lean getters do not work well in current mongo driver,
may upgrade driver version later
> Fix lean getters do not work well in current mongo driver

- scripts/installCommonDeps.sh
- scripts/module_test.js
- scripts/pack.js
- source/agent/video/compile_svtHevcEncoder.sh
- source/agent/video/videoMixer/videoMixer_sw/binding.sw.gyp
- source/agent/video/videoTranscoder/videoAnalyzer_sw/binding.sw.gyp
- source/agent/video/videoTranscoder/videoTranscoder_sw/binding.sw.gyp
- source/core/owt_base/SVTHEVCEncoder.h
Change SVT-HEVC dependency path and add no-pseudo option in packing
> Change SVT-HEVC dependency path and add no-pseudo option in packing

- docker/Dockerfile
Signed-off-by: Geoff Gustafson <geoff@linux.intel.com>
> Use stable apt commands in docker script (avoids warning)

- scripts/release/install_ffmpeg.sh
- source/agent/audio/compile_ffmpeg_with_libfdkaac.sh
Add pkg-config for building ffmpeg
> Add a missing dependency for building ffmpeg

- source/core/owt_base/VideoFrameConstructor.cpp
- source/core/owt_base/VideoFramePacketizer.cpp
> Update transport-cc map

- source/core/owt_base/VideoFrameConstructor.cpp
- source/core/owt_base/VideoFramePacketizer.cpp
Reverts open-webrtc-toolkit/owt-server#158
> Revert "Update transport-cc map (#155)"

- source/agent/webrtc/agent.toml
- source/agent/webrtc/wrtcConnection.js
Add config item for chosing first h264 profile
> Add config item for chosing first h264 profile

- scripts/release/install_ffmpeg.sh
- scripts/release/install_node.sh
- source/agent/audio/compile_ffmpeg_with_libfdkaac.sh
Fix deps missing on clean docker
> Fix deps missing on clean docker

- doc/doxygen_cfrc.conf
- doc/doxygen_cp.conf
- doc/doxygen_rest.conf
- scripts/release/package.mcu.json
- source/agent/analytics/package.json
- source/agent/conference/package.json
- source/agent/package.json
- source/agent/webrtc/package.json
- source/cluster_manager/package.json
- source/management_api/package.json
- source/management_console/package.json
- source/portal/package.json
- source/sip_portal/package.json
> Update version to 4.2.1

- source/portal/socketIOServer.js
Fix undefined client id when leave
> Fix undefined client id when leave

- scripts/pack.js
Add option to pack with ffmpeg libs
> Add option to pack with ffmpeg libs

- source/portal/socketIOServer.js
Fix ICE failure due to socket io disconnect
> Fix ICE failure due to socket io disconnect

- test/ubuntuserver.jenkinsfile
Update ubuntu's Jenkins file about owt-server to create a new podTemplateand not conflict with centos's podTemplate
> Update ubuntu's Jenkins file about server to create a new podTemplate

- source/agent/conference/accessController.js
- source/agent/conference/conference.js
- source/agent/conference/dist.json
- source/agent/conference/roomController.js
- source/agent/conference/stream.js
- source/agent/webrtc/connection.js
- source/agent/webrtc/index.js
- source/agent/webrtc/log4cxx.properties
- source/agent/webrtc/log4js_configuration.json
- source/agent/webrtc/wrtcConnection.js
- source/portal/dist.json
- source/portal/log4js_configuration.json
- source/portal/requestDataValidator.js
- source/portal/socketIOServer.js
- source/portal/v10Client.js
- source/portal/v11Client.js
> Add simulcast logic

- doc/Client-Portal Protocol.md
- doc/servermd/RESTAPI.md
Signal message format change for simulcast streams
> Signal message format change for simulcast streams

- source/agent/conference/conference.js
- source/agent/conference/stream.js
- source/management_api/resource/streamsResource.js
- source/portal/v10Client.js
- source/portal/v11Client.js
> Use correct format for specified version interface

- source/agent/webrtc/sdp.js
> Use first H264 profile when negotiating SDP

- source/agent/webrtc/sdp.js
- source/agent/webrtc/webrtcLib/VideoFrameConstructorWrapper.cc
- source/agent/webrtc/webrtcLib/VideoFramePacketizerWrapper.cc
- source/agent/webrtc/wrtcConnection.js
- source/core/owt_base/VideoFrameConstructor.cpp
- source/core/owt_base/VideoFrameConstructor.h
- source/core/owt_base/VideoFramePacketizer.cpp
- source/core/owt_base/VideoFramePacketizer.h
> Use dynamic extension ID for transport-cc

- source/agent/webrtc/sdp.js
Follow payload order in offer SDP's m line
> Follow payload order in offer SDP's m line

- source/agent/webrtc/sdp.js
Filter 10-bit VP9 in answer SDP
> Filter 10-bit VP9 in answer SDP

- scripts/build.js
Build without MSDK when it is not installed
> Build without MSDK when it is not installed

- source/agent/addons/quicIO/QuicTransport.cc
- source/core/owt_base/LiveStreamIn.cpp
- source/core/owt_base/LiveStreamIn.h
- source/management_api/resource/servicesResource.js
> Fix latest scanning issues

- source/agent/webrtc/sdp.js
Fix issue when there is only one payload number
> Fix issue when there is only one payload number

- source/agent/webrtc/log4js_configuration.json
- source/agent/webrtc/sdp.js
- source/agent/webrtc/wrtcConnection.js
Add legacy simulcast support for Safari
> Add legacy simulcast support for Safari

- source/agent/webrtc/sdp.js
Fix SDP failure with only one audio codec
> Fix SDP failure with only one audio codec

- source/agent/conference/stream.js
- source/agent/webrtc/wrtcConnection.js
Fix portal stream format is not correct sometimes
> Update correct stream descriptions

- source/agent/conference/stream.js
Remove duplicate resolutions in mix stream info
> Remove duplicate resolutions in mix stream info

- doc/servermd/Server.md
> Update browser versions

- doc/doxygen_cfrc.conf
- doc/doxygen_cp.conf
- doc/doxygen_rest.conf
- scripts/release/package.mcu.json
- source/agent/analytics/package.json
- source/agent/conference/package.json
- source/agent/package.json
- source/agent/webrtc/package.json
- source/cluster_manager/package.json
- source/management_api/package.json
- source/management_console/package.json
- source/portal/package.json
- source/sip_portal/package.json
> Update version to 4.3.0

- doc/Client-Portal Protocol.md
- doc/servermd/RESTAPI.md
- source/agent/conference/conference.js
- source/management_api/api.js
- source/management_api/resource/v1.1/index.js
- source/management_api/resource/v1.1/streamsResource.js
- source/management_api/resource/v1/analyticsResource.js
- source/management_api/resource/v1/index.js
- source/management_api/resource/v1/participantsResource.js
- source/management_api/resource/v1/recordingsResource.js
- source/management_api/resource/v1/roomResource.js
- source/management_api/resource/v1/roomsResource.js
- source/management_api/resource/v1/sipcallsResource.js
- source/management_api/resource/v1/streamingOutsResource.js
- source/management_api/resource/v1/streamsResource.js
- source/management_api/resource/v1/tokensResource.js
> Versioning REST API

- doc/servermd/Server.md
Remove useless description in document
> Remove useless description in document

- doc/servermd/Server.md
Update browser versions in doc
> Update browser versions in doc

- source/agent/webrtc/wrtcConnection.js
Fix transport-cc ID issue in simulcast streams
> Fix transport-cc ID issue in simulcast streams

- scripts/patches/licode/0010-Enable-REMB-for-RID-streams.patch
- source/agent/webrtc/log4cxx.properties
- source/agent/webrtc/sdp.js
- source/agent/webrtc/webrtcLib/binding.gyp
- source/agent/webrtc/wrtcConnection.js
- source/core/owt_base/VideoFrameConstructor.cpp
- source/core/owt_base/VideoFrameConstructor.h
> Use REMB for RID streams

- test/server.jenkinsfile
- test/ubuntuserver.jenkinsfile
> Using K8S PV mechanism to mount dependencies and resources in CI pipeline

- source/management_console/public/js/index.js
Remove unused code in console page
> Remove unused code in console page

- docker/gst/README
- source/agent/analytics/videoGstPipeline/VideoGstAnalyzer.cc
- source/agent/analytics/videoGstPipeline/VideoGstAnalyzer.h
Remove un-neccessary print and cleanups.
> Remove un-neccessary print and cleanups

- test/server.jenkinsfile
- test/ubuntuserver.jenkinsfile
> add a new stage

- test/server.jenkinsfile
- test/ubuntuserver.jenkinsfile
> Fix stage name

- test/server.jenkinsfile
- test/ubuntuserver.jenkinsfile
> delete not use stage

- test/server.jenkinsfile
- test/ubuntuserver.jenkinsfile
update jenkinsfile to match latest CI pipeline
> update jenkinsfile to match latest CI pipeline

- scripts/installDeps.sh
These messages just looked like build output, not clear that the
script is waiting for user input.
> Add press enter messages to clarify that script is paused

- source/core/owt_base/RawTransport.cpp
There is issue with if condition checking for address_in_use case.
> Fix for incorrect checking of error

- scripts/installCommonDeps.sh
- scripts/patches/libnice014-closelock.patch
- scripts/patches/licode/0013-Change-IOThreadPool-as-thread-pool-for-g_main_loop-i.patch
- source/agent/addons/mediaFrameMulticaster/binding.gyp
- source/agent/audio/audioMixer/binding.gyp
- source/agent/sip/sipIn/binding.sip.gyp
- source/agent/video/videoMixer/videoMixer_msdk/binding.msdk.gyp
- source/agent/video/videoMixer/videoMixer_sw/binding.sw.gyp
- source/agent/video/videoTranscoder/videoAnalyzer_sw/binding.sw.gyp
- source/agent/video/videoTranscoder/videoTranscoder_msdk/binding.msdk.gyp
- source/agent/video/videoTranscoder/videoTranscoder_sw/binding.sw.gyp
- source/agent/webrtc/configLoader.js
- source/agent/webrtc/index.js
- source/agent/webrtc/rtcFrame/binding.gyp
- source/core/common/JobTimer.cpp
- source/core/common/JobTimer.h
- source/core/owt_base/TaskRunnerPool.cpp
- source/core/owt_base/TaskRunnerPool.h
- source/core/rtc_adapter/AudioSendAdapter.cc
- source/core/rtc_adapter/VideoSendAdapter.cc
* Refine threads in WebRTC connections
* Use single thread for job timer
* Task runner pool
* Add patch for libnice bugs during closing
* Rebase on master
> Refine threads in WebRTC connections

- source/agent/conference/conference.js
> Fix updating permission works on roles

- source/core/rtc_adapter/RtcAdapter.h
rtcadapter handle leak. see #670
> fix rtcadapter handle leak

- source/core/owt_base/MsdkFrameEncoder.cpp
> Turn off AdaptiveLTR

- source/agent/conference/conference.js
- source/portal/versions/portalDataAdapter.js
> Allow legacy subscription to simulcast stream

- source/portal/index.js
- source/portal/portal.toml
- source/portal/socketIOServer.js
> Fix socket.io 2.4.0 cors issue

- source/agent/conference/conference.js
> Fix VAD not working issue

- scripts/patches/licode/0021-Allow-SDP-info-re-init.patch
> Fix random subscription failure

- source/core/rtc_adapter/thread/StaticTaskQueueFactory.cc
> Fix a memory leak issue due to StaticTaskQueueFactory

- source/agent/quic/dist.json
> Add makeRPC.js to quic-agent.

- source/agent/sip/sipCallConnection.js
> Fix arguments for SIP video frame packetizer

- docker/Dockerfile
+ added missing patch (based on https://github.com/open-webrtc-toolkit/owt-server/blob/master/scripts/patches/libnice014-closelock.patch)
+ added missing dependency
+ removed unnecessary ARG values
/cc @qwu16
> Updated docker file

- doc/design/quic-programming-guide.md
WebTransport is disabled by default.
> Add a step in QUIC guide to enable WebTransport at server side.

- source/data_access/index.js
initdb.js already add mongodb prefix
> Fix mongodb prefix when initdb.js change db address

- source/agent/conference/roomController.js
> Fix a type error when a WebTransport stream is published.

- source/agent/analytics/log4cxx.properties
- source/agent/analytics/log4js_configuration.json
- source/agent/audio/log4cxx.properties
- source/agent/audio/log4js_configuration.json
- source/agent/quic/log4js_configuration.json
- source/agent/recording/dist.json
- source/agent/recording/index.js
- source/agent/recording/log4cxx.properties
- source/agent/recording/log4js_configuration.json
- source/agent/streaming/dist.json
- source/agent/streaming/index.js
- source/agent/streaming/log4cxx.properties
- source/agent/streaming/log4js_configuration.json
- source/agent/video/log4cxx.properties
- source/agent/video/log4js_configuration.json
- source/agent/webrtc/log4js_configuration.json
Set default log level for internal spreading
> Fix streaming-in issue caused by internal spreading

- source/agent/conference/quicController.js
QUIC agent works similar as portal, listens on a specific port.
> Don't recycle QUIC agent.

- source/agent/addons/quic/QuicTransportConnection.cc
- source/agent/addons/quic/QuicTransportConnection.h
- source/agent/addons/quic/quic_sdk_url
- source/agent/quic/index.js
- source/agent/quic/webtransport/quicTransportServer.js
> Add close method to WebTransport session.

- scripts/patches/0001-Implement-RtcpFOVObserver.patch
fix the DEBUG build
Signed-off-by: Tiger Meng <xiao.xi.meng@intel.com>
> media_ssrc must not be zero

- source/management_console/index.js
if used through a proxy (nginx etc)
> issue with cookies

- scripts/installCommonDeps.sh
> security upgrade deps lib

- source/agent/connections.js
> Fix an issue which passes wrong value to removeDestination.

- source/agent/video/videoCapability.js
- source/management_console/public/js/App.js
Chrome95 + version push stream failed and does not support av1x negotiation
> forward stream supports AV1 for chrome95+

- source/agent/conference/roomController.js
error occurs in rebuildVideoMixer method
> fix #1185,fix rebuildVideoMixer method

- source/cluster_manager/clusterManager.js
- source/common/amqpClient.js
When I start cluster_manager master,and then start cluster_manager slave,the later's log show 'Lose heart-beat from master.' and then exit unexpectedly.
> fix #1212,cluster_manager slave exit unexpectedly

- source/agent/analytics/configLoader.js
- source/agent/audio/configLoader.js
- source/agent/conference/configLoader.js
- source/agent/quic/configLoader.js
- source/agent/recording/configLoader.js
- source/agent/sip/configLoader.js
- source/agent/streaming/configLoader.js
- source/agent/video/configLoader.js
- source/agent/webrtc/configLoader.js
I think there are some typos. Were they intentional?
> chore: fix typo

- source/agent/conference/package.json
- source/management_api/package.json
- source/portal/package.json
- source/sip_portal/package.json
- test/restTestCasesKarma/package.json
- test/restTestCasesKarma/scripts/authorization/init/package.json
package.json  update  "mongoose:5.13.15" and  "karma:6.3.16"
> update  version "mongoose:5.13.15" and  "karma:6.3.16"

- doc/design/quic-cascading.md
- source/agent/conference/agent.toml
- source/agent/conference/conference.js
- source/cluster_manager/clusterManager.js
- source/cluster_manager/cluster_manager.toml
- source/cluster_manager/index.js
- source/management_api/api.js
- source/management_api/management_api.toml
> Add configuration to enable/disable cascading feature and set cascading logs to debug

- docker/Dockerfile
Without this commit, the analytics agent will not work because of lacking so file.
> fix analytics agent problem of docker image
