source/agent/workingNode.js
The network_interfaces configuration key in agent.tom does not match the code.
=> Fix: webrtc-agent network_interfaces configuration invalid.

source/core/owt_base/SVTHEVCEncoder.cpp, source/core/owt_base/SVTHEVCEncoder.h
1. Init SVT HEVC Encoder async to avoide rpc timeout
2. Set latencyMode
3. Disable hierarchicalLevels
4. Reduce GOP to optimize latency
5. Drain bitstream after each SendPicture
=> Optimize SVT HEVC Encoder

source/agent/webrtc/configLoader.js, source/agent/webrtc/wrtcConnection.js
JSON.stringify can not apply to RegExp object. So private_ip_match_pattern is lost when agent pass it to webrtc nodeManager. 
Fix solution is change the type of private_ip_match_pattern from RegExp to string.
=> Fix: Invalid config webrtc.network_interface.replaced_ip_address.

doc/servermd/Server.md
Add missing instructions in doc
=> Add missing instructions in doc

source/core/owt_base/VideoFrameConstructor.cpp, source/core/owt_base/VideoFrameConstructor.h, source/core/rtc_adapter/VieReceiver.cc, source/core/rtc_adapter/VieReceiver.h
With this we enable transport-cc feedback to publisher. We still don't handle transport-cc feedbacks from subscriber, as we're not adjusting bitrate on subscriber bandwidth change.
=> Enabling sending transport-cc feedback from MCU to publisher.

README.md, scripts/build.js
1. In Ubuntu server with less than 8 cores, `-j 8` would hang the build process, using the number of cores could fix it;
2. Update scripts according to the new owt-client-javascript structure;
=> Fix build and pack issue.

docker/Dockerfile, docker/conference/Dockerfile-conference, docker/conference/docker-compose.yml
Adding Dockerfile and use docker compose to build owt-server in the docker container.  You can simply run docker-compose build to build the base image and docker-compose up to start the server with the conference sample, this helps resolve #16.
=> Adding docker support for basic example

source/agent/webrtc/configLoader.js
For docker to pass variable by ENV:
```bash
[webrtc]
network_interfaces = [{name="eth0",replaced_ip_address="$DOCKER_HOST"}]  # default: []
```
We can pass the host and ip to docker:
```
docker run -it -p 3004:3004 -p 3300:3300 -p 8080:8080 -p 60000-60050:60000-60050/udp \
--env=DOCKER_IP:192.168.1.4 \
registry.cn-hangzhou.aliyuncs.com/ossrs/owt:4.3 bash
```
Then, the portal config will be replaced as:
```bash
[webrtc]
network_interfaces = [{name="eth0",replaced_ip_address="192.168.1.4"}]  # default: []
```
The logs:
```bash
starting webrtc-agent, stdout -> /tmp/git/owt-docker/owt-server-4.3/dist/logs/webrtc-agent.stdout
ENV: config.webrtc.network_interfaces[eth0].replaced_ip_address=192.168.1.4
```
=> Support config webrtc agent ip_address by env

source/portal/index.js
For docker to pass variable by ENV:
```bash
[portal]
hostname = "$DOCKER_HOST" #default: ""
ip_address = "$DOCKER_IP" #default: ""
```
We can pass the host and ip to docker:
```
docker run -it -p 3004:3004 -p 3300:3300 -p 8080:8080 -p 60000-60050:60000-60050/udp \
--env=DOCKER_HOST:owt-docker.me --env=DOCKER_IP:192.168.1.4 \
registry.cn-hangzhou.aliyuncs.com/ossrs/owt:4.3 bash
```
Then, the portal config will be replaced as:
```bash
[portal]
hostname = "owt-docker.me" #default: ""
ip_address = "192.168.1.4" #default: ""
```
The logs:
```bash
starting portal, stdout -> /tmp/git/owt-docker/owt-server-4.3/dist/logs/portal.stdout
2020-03-03 05:01:41.861  - INFO: Main - ENV: config.portal.ip_address=192.168.1.4
2020-03-03 05:01:41.861  - INFO: Main - ENV: config.portal.hostname=owt-docker.me …
```
=> Support config portal hostname and ip_address by env

README.md, doc/servermd/Server.md, docker/Dockerfile, docker/conference/Dockerfile-conference, docker/conference/build_server.sh, docker/conference/docker-compose.yml, scripts/pack.js, scripts/release/daemon-bin.sh, scripts/release/daemon-mcu.sh, source/management_api/initdb.js, test/restTestCasesKarma/karma.conf.js
Now the app maker doesn't need to have a deep
understanding of the owt-server file system. They can simply run
build_server.sh and it will take care of the rest. Also, now apps
can use whatever name they want for the main JS file, rather than
the hard coded samplertcservice.js. It also allows the app maker
to name the final Docker image what they.
=> Make installing an app into the owt-server Docker image much easier.

scripts/installCommonDeps.sh
I just submitted this for 4.3.x but see the same problem exists on master.
=> Fix broken download of openssl-1.0.2t.tar.gz

scripts/pack.js
When the ldd command here returned something like:
sipLib.so => not found
the previous code would report a cryptic error:
Error: Command failed: [ -s not ]
=> Give helpful warning when ldd doesn't find a dependency

source/common/amqp_client.js
1. 2 cluster_manager, one for master, another for slave.
2. cluster_manager stop working and whole cluster stopped service.
=> fix: cluster_manager stop working if !!Double master!! status occur

scripts/pack.js
QUIC agent was restored as an experimental feature in an earlier change. To enable QUIC agent, please build and pack conference server with following commands:
```
./scripts/build.js -t quic -t <mcu or other target>
./scripts/pack.js -t all -t quic-agent -p <sample web app path>
```
=> Add flags to enable QUIC agent.

source/agent/addons/quic/QuicTransportStream.cc, source/agent/addons/quic/QuicTransportStream.h, source/agent/quic/webtransport/quicTransportServer.js, source/agent/quic/webtransport/quicTransportStreamPipeline.js
This change also closes unauthenticated connections in expected time and avoid duplicated signaling streams.
=> Implement close for QUIC stream.

source/management_api/initdb.js
Because of wrong URL concatenation the MongoDB URL is wrong and initdb.js script fails on execution.
=> Fix for wrong MongDB URL

scripts/installCommonDeps.sh, source/agent/addons/quic/binding.gyp
Fix failed to build QUIC agent because of missing header files.
=> Copy QUIC SDK headers to build directory.

scripts/installCommonDeps.sh, scripts/install_nvm.sh
=> update 4 years old nvm and fix openssl lib64 issue in centos 7

doc/Client-Portal Protocol.md, source/portal/socketIOServer.js
Requires as less info as possible.
In P2P mode, instead of using browser version to determine whether a
feature is supported by remote side or not, we use capability map to
indicate whether a feature is supported.
=> Don't require os and runtime info.

source/agent/nodeManager.js
* **Prevent that undefined ends up in the nodes array**
In the case where there was no available node after the rejection of the promise, the value `undefined` was pushed into the `nodes` array. This has caused the node array to have values that shouldn't be there. This was one of the reasons that fillNodes wasn't called anymore even when the idle_nodes was empty and the number of running nodes had not reached the limit.
* **Do not start more nodes than maxNodeNum**
After a node has been closed, the fillNodes function was called without any checks. Because of this, it did always fill up the array to `spec.prerunNodeNum` nodes. This caused that it was possible to have 10 nodes running while the limit was configured to 5.
=> Resolve pooling issues in nodeManager

source/agent/index.js, source/agent/nodeManager.js
We had the following scenario today:
```
2021-05-11 21:41:08.630  - INFO: ClusterWorker - Lost connection with cluster owt-cluster
2021-05-11 21:41:09.540  - WARN: AmqpClient - Late rpc reply: { data: 'whoareyou', corrID: 49019, type: 'callback' }
2021-05-11 21:41:09.541  - WARN: AmqpClient - Late rpc reply: { data: 'whoareyou', corrID: 49020, type: 'callback' }
2021-05-11 21:41:09.541  - WARN: AmqpClient - Late rpc reply: { data: 'whoareyou', corrID: 49021, type: 'callback' }
2021-05-11 21:41:09.541  - WARN: AmqpClient - Late rpc reply: { data: 'whoareyou', corrID: 49022, type: 'callback' }
2021-05-11 21:41:09.541  - WARN: AmqpClient - Late rpc reply: { data: 'whoareyou', corrID: 49023, type: 'callback' }
2021-05-11 21:41:09.541  - INFO: WorkingAgent - webrtc agent lost.
2021-05-11 …
```
=> Correctly recover the nodeManager after agent recovery

source/common/clusterWorker.js
We had a loss of the video agent which never recovered. Here are the logs:
```
2021-06-02 03:34:43.523  - INFO: ClusterWorker - Unknown by cluster manager owt-cluster
2021-06-02 03:34:43.568  - INFO: WorkingAgent - video agent lost.
2021-06-02 03:34:43.569  - INFO: ClusterWorker - Rejoin cluster owt-cluster OK.
2021-06-03 07:56:53.538  - ERROR: NodeManager - getNode error: No available node
2021-06-03 07:57:03.328  - ERROR: NodeManager - getNode error: No available node
2021-06-03 07:57:08.875  - ERROR: NodeManager - getNode error: No available node
2021-06-03 07:57:09.472  - ERROR: NodeManager - getNode error: No available node
2021-06-03 07:57:14.972  - ERROR: NodeManager - getNode error: No available node
2021-06-03 07:57:18.193  - ERROR: NodeManager - getNode error: No available node …
```
=> Correctly recover agent on first attempt after a loss

source/common/amqpClient.js
`msg` is defined in try statement, not defined in catch statement.
=> Fix an ReferenceError.

docker/Dockerfile
patch file libnice014-closelock.patch dose not exists in version 4.3
bash: owt-server-4.3/scripts/patches/libnice014-closelock.patch: No such file or directory
=> fix docker libnice014-closelock.patch not found

source/agent/addons/quic/QuicTransportStream.cc, source/agent/addons/quic/QuicTransportStream.h, source/agent/quic/webtransport/quicTransportServer.js
If signaling data is arrived before ondata handler is assigned, it will
not fire ondata again since OnCanRead is not called when readable queue
is not empty.
Ref: #1053.
=> Check readable data after ondata handler is assigned.

source/core/owt_base/LiveStreamIn.cpp
Some rtsp server will handle the second PLAY request
as error and disconnect the TCP connection, it will
cause the stream disconnect and trigger the reconnect
mechnism in LiveStream, continue to disconnect and
reconnect.
Signed-off-by: Yu, Dingfeng <dingfeng.yu@intel.com>
=> Remove av_read_play which already called inside rtsp

source/agent/addons/quic/QuicTransportConnection.h, source/agent/addons/quic/quic_sdk_url, source/agent/quic/e2e-test/js/webtransport.js
This change overrides a pure virtual function with empty implementation. This function will be implemented in another change for datagram support. It also uses `serverCertificateHashes` instead of `serverCertificateFingerprints` because of API change.
=> Fix WebTransport E2E test failures.

source/agent/quic/package-lock.json, source/agent/quic/package.json
Reverts open-webrtc-toolkit/owt-server#1150
Revert this change because the server doesn't support newer version of log4js. CI failed for the original PR.
https://github.com/open-webrtc-toolkit/owt-server/runs/4905019378?check_suite_focus=true#step:14:34
=> Revert "Bump log4js from 1.1.1 to 6.4.0 in /source/agent/quic"

source/agent/addons/quic/test/package-lock.json, source/agent/addons/quic/test/package.json
Reverts open-webrtc-toolkit/owt-server#1149
Revert this change because the server doesn't support newer version of log4js. CI failed for the original PR.
https://github.com/open-webrtc-toolkit/owt-server/runs/4916556279?check_suite_focus=true#step:14:34
=> Revert "Bump log4js from 1.1.1 to 6.4.0 in /source/agent/addons/quic/test"

.github/CODEOWNERS, .github/dependabot.yml
It avoids Dependabot to creates too many PRs. Security updates are not affected.
=> Add a configuration file for Dependabot.

.github/workflows/webtransport.yaml, doc/design/quic-agent.md, source/agent/addons/quic/test/scripts/generate-certs.sh
WebTransport custom certificate verification doesn't support RSA now.
=> Use certificate with public key algorithm ECDSA for testing.

scripts/installCommonDeps.sh
The download link for 1.2.11 is unavailable.
Fixes #1189.
=> Bump zlib from 1.2.11 to 1.2.12.

source/agent/addons/quic/WebTransportFrameDestination.cc, source/agent/addons/quic/WebTransportFrameDestination.h, source/agent/quic/agent.toml, source/agent/quic/index.js, source/agent/quic/webtransport/quicTransportServer.js
Unlike media data over datagrams, this change allows sending media data
in a reliable way for some special cases that packet drop is not
acceptable.
=> Enable sending media data over WebTransport streams.

source/agent/addons/quic/QuicTransportStream.cc
QUIC agent cannot decide how to deal with the data if sending queue is
full as it doesn't understand the meaning of the data.
=> Check return value of WebTransport stream write.

source/common/amqpClient.js
=> fix amqpClient.js not handle close event.

scripts/installCommonDeps.sh
The download link "https://zlib.net/zlib-1.2.12.tar.gz" is invalid
=> zlib version update 1.2.13  

.github/workflows/webtransport.yaml, scripts/installDeps.sh, scripts/installDepsUnattended.sh, scripts/installUbuntuDeps.sh, source/core/owt_base/internal/TransportClient.cpp, source/core/owt_base/internal/TransportServer.cpp
Fix #1246.
Apt installs a newer version of boost for Ubuntu 20.04. This change also removes the use of deprecated boost APIs for internal IO so an old version of boost is not needed for WebTransport tests.
=> Run WebTransport tests on Ubuntu 20.04.

source/management_console/package.json, source/portal/package.json
OWT-MCU-Portal upgrade socket.io from 3.1.2 to 4.5.0
OWT-MCU-Manage-Console upgrade express from 4.16.4 to 4.17.3
=> Portal upgrade socket.io from 3.1.2 to 4.5.0 ;  Manage-Console upgrade express from 4.16.4 to 4.17.3

.github/workflows/webtransport.yaml
It looks like some dependencies don't work with Python 3.11.
=> Run WebTransport E2E test with Python 3.10

source/agent/index.js
variable `task` is not defined before
=> fix: add missing parameter

source/portal/socketIOServer.js
If different client version (eg: v1.2,v1.1)  in one room ,the converted data was incorrectly sent to the v1.2 client. So make a deep copy before the message is sent , to prevent the data reference changing by portalDataAdapter in other client session.
=> deep clone data before notify to clients

source/management_api/init.sh
``` bash
MONGO=mongodb+srv://owt:qwer4321Tig@mongodb-svc.default.svc.cluster.local/owt?replicaSet=mongodb&ssl=false
echo dburl=$MONGO | cut -d '=' -f 2
echo dburl=$MONGO | cut -d '=' -f 2-
```
Without this pr, if I send the argument dburl with a mongo connect string with parameters to shell management-api/init.sh, the connect string is truncated and become a illegal mongo connect string.
=> fix wrong truncation of DB_URL

source/cluster_manager/index.js
The other config fields are initialized, this one not which raises errors if the agents toml doesn't include the cascading section.
=> Initialize config.cascading in cluster_manager
